
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEQ = 47;
  public static final int STRING_LITERAL = 48;
  public static final int POWER = 61;
  public static final int MULT = 33;
  public static final int CHAR = 6;
  public static final int TCHAR = 50;
  public static final int POOL = 37;
  public static final int TFLOAT = 52;
  public static final int INTEGER = 2;
  public static final int LPAREN = 29;
  public static final int INIT = 24;
  public static final int FOR = 19;
  public static final int MINUS = 32;
  public static final int RPAREN = 45;
  public static final int AND = 4;
  public static final int RANGE = 41;
  public static final int LT = 30;
  public static final int RIGHTSQ = 44;
  public static final int ELT = 13;
  public static final int ILLEGAL_CHARACTER = 12;
  public static final int TDEF = 51;
  public static final int OR = 35;
  public static final int IN = 23;
  public static final int QMARK = 39;
  public static final int COMMA = 8;
  public static final int TBOOL = 49;
  public static final int SEMICOL = 46;
  public static final int FI = 17;
  public static final int DIV = 10;
  public static final int RAT = 40;
  public static final int CONCATE = 9;
  public static final int LEFTSQ = 26;
  public static final int PLUS = 36;
  public static final int LOOP = 28;
  public static final int MAIN = 31;
  public static final int IF = 22;
  public static final int DOT = 60;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int EQUAL = 14;
  public static final int TRUE = 57;
  public static final int LAMBDA = 25;
  public static final int error = 1;
  public static final int BREAK = 5;
  public static final int FDEF = 16;
  public static final int LCB = 58;
  public static final int TOP = 55;
  public static final int TINT = 54;
  public static final int COLON = 7;
  public static final int ELSE = 11;
  public static final int READ = 42;
  public static final int FLOAT = 18;
  public static final int THEN = 53;
  public static final int LEN = 27;
  public static final int ALIAS = 3;
  public static final int TRAT = 56;
  public static final int FALSE = 15;
  public static final int RCB = 59;
  public static final int GT = 20;
  public static final int PRINT = 38;
  public static final int NOTEQ = 34;
  public static final int IDENTIFIER = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "ALIAS",
  "AND",
  "BREAK",
  "CHAR",
  "COLON",
  "COMMA",
  "CONCATE",
  "DIV",
  "ELSE",
  "ILLEGAL_CHARACTER",
  "ELT",
  "EQUAL",
  "FALSE",
  "FDEF",
  "FI",
  "FLOAT",
  "FOR",
  "GT",
  "IDENTIFIER",
  "IF",
  "IN",
  "INIT",
  "LAMBDA",
  "LEFTSQ",
  "LEN",
  "LOOP",
  "LPAREN",
  "LT",
  "MAIN",
  "MINUS",
  "MULT",
  "NOTEQ",
  "OR",
  "PLUS",
  "POOL",
  "PRINT",
  "QMARK",
  "RAT",
  "RANGE",
  "READ",
  "RETURN",
  "RIGHTSQ",
  "RPAREN",
  "SEMICOL",
  "SEQ",
  "STRING_LITERAL",
  "TBOOL",
  "TCHAR",
  "TDEF",
  "TFLOAT",
  "THEN",
  "TINT",
  "TOP",
  "TRAT",
  "TRUE",
  "LCB",
  "RCB",
  "DOT",
  "POWER"
  };
}

